[package]
name = "day-12"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cached = "0.46.1"
nom = "7.1.1"
utils = { path = "../utils", version = "*" }
